controllers:
    resource: ../src/Controller/
    type: attribute

index:
    path: /
    controller: App\Controller\UserController::index2
    methods: GET

user_index:
    path: /api/user
    controller: App\Controller\UserController::index
    methods: GET

api_login_check:
    path: /api/login_check
    controller: App\Controller\AuthController::getTokenUser
    methods: POST

#User routes
register_user:
    path: /register_user
    controller: App\Controller\AuthController::registerUser
    methods: POST

register_client:
    path: /register_client
    controller: App\Controller\AuthController::register
    methods: POST

client_api_login_check:
    path: /client_api/login_check
    controller: App\Controller\AuthController::getTokenclient
    methods: POST
